### ISSUE TITLE
Does not install on SFOS 3.2.1

### ISSUE THREAD

**Issue by Olf0** [mkiol/dskeyboard#1]
Unfortunately, `harbour-dskeyboard-1.1.0-1.noarch.rpm` fails to install on SailfishOS 3.2.1 with `Nothing provides libstdc++.so.6(CXXABI_1.3.9) needed by ...`.
AFAICS from the spec-file, this is not a dependency of dskeyboard proper, but introduced by the build system (SailfishOS-SDK etc.).

If my analysis is correct, please recompile it, so it also installs on older SailfishOS releases.
The same applies to dsnotes.

**Comment by mkiol** [comment]
Sorry for veeery late reply.

Actually, `harbour-dskeyboard` package requires `harbour-dsnote >= 1.6.0` and `harbour-dsnote` depends on `libstdc++.so.6(CXXABI_1.3.9)`.

I will check if I can recompile `harbour-dsnote` with older SFOS SDK.

**Comment by mkiol** [comment]
Unfortunately I can't support SailfishOS 3.2.1 because GCC is too old. 

```
[SB2 sdk-build SailfishOS-3.2.1.20-armv7hl] $ g++ --version
armv7hl-meego-linux-gnueabi-g++ (Linaro GCC 4.9-2017.01) 4.9.4 20160726 (Mer 4.9.4-1)
```

The code uses some c++17 features and GCC 4.9 is not able to compile it. It appears that support for c++17 was added from GCC 5.

**Comment by Olf0** [comment]
Thank you for your efforts and the analysis.
<sub>Still sad, though. :disappointed:</sub>
